// Clean-room implementation from OFFLATTICE_OTF_KMC_SPEC_V1 + ERRATA_1 + ERRATA_2_PARITY.
// Independently authored; no implementation source consulted.
use crate::checkpoint::{canonical_json_bytes,parse_strict_json,portable_integer_violation};
use crate::identity::{closest_periodic_vector,hex_sha256};
use crate::model::{Cell,Vec3};
use crate::rng::PhiloxState;
use crate::status::{Severity,StatusCode};
use serde::{Deserialize,Serialize};
use serde_json::{Map,Value};
use std::collections::{BTreeMap,BTreeSet};
use std::fs::{self,File,OpenOptions};
use std::io::Write;
use std::path::{Component,Path,PathBuf};
use std::sync::atomic::{AtomicU64,Ordering};

pub const JSON_API:&str="spark-atomistic-json/1";
pub const SCHEMA_DIGEST:&str="sha256:583d580d54e3847ef92f1b1456dda006161689c0bac27fd7ea896a093f48c02c";
pub const IDENTITY_VERSION_V2:&str="spark-state-identity/2";
const MAX_PORTABLE:u64=9_007_199_254_740_991;

#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]
pub struct WireModel{pub schema:WireSchema,pub system:WireSystem,pub calculator:WireCalculator,pub relaxation:WireRelaxation,pub saddle_search:WireSaddleSearch,pub discovery:WireDiscovery,pub kinetics:WireKinetics,pub resources:WireResources,pub output:WireOutput,pub basin:WireBasin,#[serde(default,skip_serializing_if="Map::is_empty")]pub metadata:Map<String,Value>}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireSchema{pub id:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireConstraints{pub kind:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]
pub struct WireSystem{pub atom_ids:Vec<String>,pub species:Vec<String>,pub positions:Vec<Vec3>,pub cell:Cell,pub pbc:[bool;3],pub movable:Vec<bool>,pub constraints:WireConstraints,pub charge:f64,pub spin:f64,pub calculator_model_digest:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireCalculator{pub deterministic:bool,pub model_digest:String,pub model_name:String,pub model_version:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireRelaxation{pub force_tolerance:f64,pub max_evaluations:u64,pub max_steps:u64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireSaddleSearch{pub curvature_tolerance:f64,pub endpoint_displacement:f64,pub force_tolerance:f64,pub max_iterations:u64,pub method:String,pub orthogonal_directions:u64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireDiscoveryClass{pub kind:String,pub name:String,pub probability:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireCalibration{pub id:String,pub source:String,pub version:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]
pub struct WireDiscovery{pub mode:String,pub classes:Vec<WireDiscoveryClass>,pub minimum_successful:u64,pub consecutive_redundant:u64,pub maximum_attempts:u64,pub maximum_evaluations:u64,pub relevance_rate_min:f64,pub alpha:Option<f64>,pub alpha_calibration:Option<WireCalibration>}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]
pub struct WireKinetics{pub temperature:f64,pub rate_model:String,pub prefactor:f64,pub barrier_tolerance:f64,pub detailed_balance_tolerance:f64,pub log_rate_cutoff:f64,pub absorbing_ok:bool,pub maximum_steps:u64,pub run_seed:u64,pub state_rms_tolerance:f64,pub state_max_tolerance:f64,pub state_energy_tolerance_per_atom:f64,pub saddle_rms_tolerance:f64,pub saddle_max_tolerance:f64,pub saddle_energy_tolerance:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]
pub struct WireResources{pub callback_timeout_s:f64,pub catalog_events:u64,pub evaluations_per_relaxation:u64,pub evaluations_per_saddle_attempt:u64,pub output_bytes:u64,pub resident_memory_bytes:u64,pub retry_backoff_s:f64,pub retry_count:u64,pub saddle_attempts_per_state:u64,pub total_calculator_evaluations:u64,pub wall_time_s:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]
pub struct WireOutput{pub checkpoint_every_steps:u64,pub checkpoint_path:String,pub checkpoint_wall_time_s:f64,pub overwrite:bool,pub resume:bool,pub summary_path:String,pub trajectory_path:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct WireBasin{pub enabled:bool}

#[derive(Clone,Debug)]pub struct ValidatedModel{model:WireModel,config_digest:String,tolerance_digest:String,identity_digest:String,discovery_config_digest:String,resolved_paths:[PathBuf;3]}
impl ValidatedModel{pub fn model(&self)->&WireModel{&self.model}pub fn config_digest(&self)->&str{&self.config_digest}pub fn tolerance_digest(&self)->&str{&self.tolerance_digest}pub fn identity_digest(&self)->&str{&self.identity_digest}pub fn discovery_config_digest(&self)->&str{&self.discovery_config_digest}pub fn resolved_paths(&self)->&[PathBuf;3]{&self.resolved_paths}pub fn basin_requested(&self)->bool{self.model.basin.enabled}fn preflight_run(&self)->Result<(),ApiFailure>{let o=&self.model.output;for(i,p)in self.resolved_paths.iter().enumerate(){if p.exists()&&!o.overwrite&&!(i==0&&o.resume){return Err(ApiFailure::new(StatusCode::OutputExists,"E2-SCHEMA-010").in_component("output").with_detail("path",Value::String(p.display().to_string())))}}if o.resume&&!self.resolved_paths[0].exists(){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010").in_component("output").with_detail("path",Value::String(self.resolved_paths[0].display().to_string())))}Ok(())}}

impl WireModel{pub fn validate(self,source_path:Option<&Path>)->Result<ValidatedModel,ApiFailure>{
    if self.schema.id!=crate::IR_SCHEMA{return Err(ApiFailure::new(StatusCode::SchemaUnsupported,"E2-SCHEMA-002"))}let s=&self.system;let n=s.atom_ids.len();let mut ids=BTreeSet::new();if n==0||s.species.len()!=n||s.positions.len()!=n||s.movable.len()!=n||s.atom_ids.iter().any(|x|x.is_empty()||!ids.insert(x.clone()))||s.species.iter().any(String::is_empty)||!s.movable.iter().any(|x|*x)||s.constraints.kind!="fixed-mask"||s.calculator_model_digest.is_empty()||s.calculator_model_digest!=self.calculator.model_digest||!finite(s.positions.iter().flatten().copied())||!finite(s.cell.iter().flatten().copied())||!s.charge.is_finite()||!s.spin.is_finite()||det(s.cell).abs()<=1e-18{return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-003"))}
    if self.calculator.model_digest.is_empty()||self.calculator.model_name.is_empty()||self.calculator.model_version.is_empty(){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-004"))}if !positive(self.relaxation.force_tolerance)||!portable_positive(self.relaxation.max_evaluations)||!portable_positive(self.relaxation.max_steps){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-005"))}
    let saddle=[self.saddle_search.curvature_tolerance,self.saddle_search.endpoint_displacement,self.saddle_search.force_tolerance];if self.saddle_search.method!="directional-dimer"||!saddle.into_iter().all(positive)||!portable_positive(self.saddle_search.max_iterations)||!portable_positive(self.saddle_search.orthogonal_directions){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-006"))}
    validate_discovery(&self.discovery)?;validate_kinetics(&self.kinetics)?;validate_resources(&self.resources)?;let paths=validate_paths(&self.output,source_path)?;if self.relaxation.max_evaluations>self.resources.evaluations_per_relaxation||self.discovery.maximum_attempts>self.resources.saddle_attempts_per_state||self.discovery.maximum_evaluations>self.resources.total_calculator_evaluations{return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-012"))}
    let mut config=serde_json::to_value(&self).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-CAN-007"))?;config.as_object_mut().expect("wire model serializes as object").remove("metadata");let config_digest=digest_value(&config)?;let tolerance_digest=tolerance_digest(&self.kinetics)?;let identity_digest=identity_digest(&self.kinetics)?;let discovery_config_digest=digest_value(&serde_json::to_value(&self.discovery).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-DISC-004"))?)?;Ok(ValidatedModel{model:self,config_digest,tolerance_digest,identity_digest,discovery_config_digest,resolved_paths:paths})
}}
fn finite<I:Iterator<Item=f64>>(mut xs:I)->bool{xs.all(|x|x.is_finite())}fn positive(x:f64)->bool{x.is_finite()&&x>0.0}fn portable_positive(x:u64)->bool{x>=1&&x<=MAX_PORTABLE}
fn det(m:Cell)->f64{m[0][0]*(m[1][1]*m[2][2]-m[1][2]*m[2][1])-m[0][1]*(m[1][0]*m[2][2]-m[1][2]*m[2][0])+m[0][2]*(m[1][0]*m[2][1]-m[1][1]*m[2][0])}
fn validate_discovery(d:&WireDiscovery)->Result<(),ApiFailure>{if !matches!(d.mode.as_str(),"strict"|"exploratory")||d.classes.is_empty()||!portable_positive(d.minimum_successful)||!portable_positive(d.consecutive_redundant)||!portable_positive(d.maximum_attempts)||!portable_positive(d.maximum_evaluations)||!d.relevance_rate_min.is_finite()||d.relevance_rate_min<0.0{return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-007"))}let mut names=BTreeSet::new();if d.classes.iter().any(|c|!matches!(c.kind.as_str(),"global"|"local"|"targeted")||c.name.is_empty()||!names.insert(c.name.clone())||!positive(c.probability))||!d.classes.iter().any(|c|c.kind!="targeted")||(d.classes.iter().map(|c|c.probability).sum::<f64>()-1.0).abs()>1e-12{return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-007"))}match(&d.alpha,&d.alpha_calibration){(None,None)=>{},(Some(a),Some(c))if a.is_finite()&&*a>0.0&&*a<=1.0&&!c.id.is_empty()&&!c.source.is_empty()&&!c.version.is_empty()=>{},_=>return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-007"))}Ok(())}
fn validate_kinetics(k:&WireKinetics)->Result<(),ApiFailure>{let positive_values=[k.temperature,k.prefactor,k.detailed_balance_tolerance,k.state_rms_tolerance,k.state_max_tolerance,k.state_energy_tolerance_per_atom,k.saddle_rms_tolerance,k.saddle_max_tolerance,k.saddle_energy_tolerance];if k.rate_model!="COMMON_PREFACTOR"||!positive_values.into_iter().all(positive)||!k.barrier_tolerance.is_finite()||k.barrier_tolerance<0.0||!k.log_rate_cutoff.is_finite()||!portable_positive(k.maximum_steps)||k.run_seed>MAX_PORTABLE{return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-008"))}Ok(())}
fn validate_resources(r:&WireResources)->Result<(),ApiFailure>{let counts=[r.catalog_events,r.evaluations_per_relaxation,r.evaluations_per_saddle_attempt,r.output_bytes,r.resident_memory_bytes,r.saddle_attempts_per_state,r.total_calculator_evaluations];if !positive(r.callback_timeout_s)||!positive(r.wall_time_s)||r.retry_backoff_s!=0.0||r.retry_count!=0||!counts.into_iter().all(portable_positive){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-009"))}Ok(())}
fn validate_paths(o:&WireOutput,source:Option<&Path>)->Result<[PathBuf;3],ApiFailure>{if !portable_positive(o.checkpoint_every_steps)||!positive(o.checkpoint_wall_time_s){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))}let raw=[&o.checkpoint_path,&o.trajectory_path,&o.summary_path];if raw.iter().any(|x|x.is_empty()){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))}let mut out=Vec::new();for x in raw{let p=Path::new(x);let resolved=if p.is_absolute(){p.to_owned()}else{source.and_then(Path::parent).ok_or_else(||ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))?.join(p)};out.push(existing_alias_path(&lexical(&resolved))?);}if same_existing_file(&out[0],&out[1])?||same_existing_file(&out[0],&out[2])?||same_existing_file(&out[1],&out[2])?{return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))}Ok([out.remove(0),out.remove(0),out.remove(0)])}
fn lexical(p:&Path)->PathBuf{let mut out=PathBuf::new();for x in p.components(){match x{Component::CurDir=>{},Component::ParentDir=>match out.components().next_back(){Some(Component::Normal(_))=>{out.pop();},Some(Component::RootDir)|Some(Component::Prefix(_))=>{},_ if !p.is_absolute()=>out.push(".."),_=>{}},_=>out.push(x.as_os_str())}}out}
fn existing_alias_path(p:&Path)->Result<PathBuf,ApiFailure>{if p.exists(){return fs::canonicalize(p).map_err(|_|ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))}if let(Some(parent),Some(name))=(p.parent(),p.file_name()){if parent.exists(){return fs::canonicalize(parent).map(|x|x.join(name)).map_err(|_|ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))}}Ok(p.to_owned())}
fn same_existing_file(a:&Path,b:&Path)->Result<bool,ApiFailure>{if a==b{return Ok(true)}if !(a.exists()&&b.exists()){return Ok(false)}let ma=fs::metadata(a).map_err(|_|ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))?;let mb=fs::metadata(b).map_err(|_|ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-010"))?;#[cfg(unix)]{use std::os::unix::fs::MetadataExt;Ok(ma.dev()==mb.dev()&&ma.ino()==mb.ino())}#[cfg(not(unix))]{let _=(ma,mb);Ok(false)}}
fn digest_value(v:&Value)->Result<String,ApiFailure>{let b=canonical_json_bytes(v).map_err(|_|ApiFailure::new(StatusCode::NonfiniteResult,"E2-CAN-005"))?;Ok(format!("sha256:{}",hex_sha256(&b)))}
pub fn tolerance_digest(k:&WireKinetics)->Result<String,ApiFailure>{digest_value(&serde_json::json!({"barrier_tolerance":k.barrier_tolerance,"detailed_balance_tolerance":k.detailed_balance_tolerance,"log_rate_cutoff":k.log_rate_cutoff,"saddle_energy_tolerance":k.saddle_energy_tolerance,"saddle_max_tolerance":k.saddle_max_tolerance,"saddle_rms_tolerance":k.saddle_rms_tolerance,"state_energy_tolerance_per_atom":k.state_energy_tolerance_per_atom,"state_max_tolerance":k.state_max_tolerance,"state_rms_tolerance":k.state_rms_tolerance}))}
pub fn identity_digest(k:&WireKinetics)->Result<String,ApiFailure>{digest_value(&serde_json::json!({"reflection_invariant":false,"rotation_invariant":false,"state_energy_tolerance_per_atom":k.state_energy_tolerance_per_atom,"state_max_tolerance":k.state_max_tolerance,"state_rms_tolerance":k.state_rms_tolerance,"version":IDENTITY_VERSION_V2}))}

#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CapabilityRequest{pub operation:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct ValidationRequest{pub model:WireModel,pub operation:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct RunRequest{pub allow_unvalidated:bool,pub extension:Map<String,Value>,pub model:WireModel,pub operation:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct ApiContext{pub component:String,pub details:Map<String,Value>,pub requirement_id:String,pub retryable:bool,pub search_or_event_id:Option<String>,pub state_id:Option<String>}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct ApiResponse{pub causal_status:Option<StatusCode>,pub context:ApiContext,pub exit_code:i32,pub message:String,pub operation:String,pub severity:Severity,pub status:StatusCode,pub value:Option<Value>}
// `E3-STATUS-001` / `E3-STATUS-002` (normative; adopted by `D-127`). `E2-STATUS-001` fixes the
// key set of `context` but no vocabulary for `component` and no content for `details`, so this
// backend answered `"api"` / `{}` everywhere while the Python backend named the failing subsystem
// and populated a per-requirement detail object. `E2-PAR-003` ("byte-identical") cannot hold for
// both, so the proposal's recommended option (a) is implemented here: the failing subsystem is
// carried on the failure itself rather than mapped at the response boundary. Revert by deleting
// the `component` field and the `.in_component(..)`/`.with_detail(..)` call sites.
#[derive(Clone,Debug)]pub struct ApiFailure{pub status:StatusCode,pub requirement_id:String,pub component:String,pub causal_status:Option<StatusCode>,pub details:Map<String,Value>}
impl ApiFailure{pub fn new(status:StatusCode,requirement:&str)->Self{Self{status,requirement_id:requirement.into(),component:"api".into(),causal_status:None,details:Map::new()}}
    /// `E3-STATUS-001`: name the subsystem that refused the request.
    pub fn in_component(mut self,component:&str)->Self{self.component=component.into();self}
    /// `E3-STATUS-002`: one `context.details` entry.
    pub fn with_detail(mut self,key:&str,value:Value)->Self{self.details.insert(key.into(),value);self}}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct RunValue{pub checkpoint_sequence:u64,pub current_state_id:String,pub incomplete_catalog:bool,pub simulation_time_s:f64,pub step_index:u64}
pub trait RunAdapter:Send+Sync{fn run(&self,model:&ValidatedModel,extension:&Map<String,Value>)->Result<RunValue,ApiFailure>;}

pub fn dispatch_json(input:&[u8],source_path:Option<&Path>,adapter:Option<&dyn RunAdapter>)->Vec<u8>{
    let parsed=parse_public(input);let operation=parsed.as_ref().ok().and_then(|v|v.get("operation")).and_then(Value::as_str).unwrap_or("unknown").to_owned();
    let response=match parsed{
        Err(e)=>failure_response(operation,e),
        Ok(value)=>match operation.as_str(){
            "capabilities"=>match request_shape(&value,"capabilities").and_then(|()|serde_json::from_value::<CapabilityRequest>(value).map_err(|_|ApiFailure::new(StatusCode::InvalidInput,"E2-API-001"))){Ok(r)if r.operation=="capabilities"=>success_response("capabilities","E2-API-001",capability_value()),Ok(_)=>failure_response(operation,ApiFailure::new(StatusCode::InvalidInput,"E2-API-001")),Err(e)=>failure_response(operation,e)},
            // E2-SCOPE-003 ("Unknown keys in every normative object return INVALID_INPUT") is the
            // governing requirement for an unknown key, so it must be cited rather than the
            // generic request-shape rule. serde's deny_unknown_fields surfaces this as an
            // "unknown field" message; every other decode failure stays on E2-API-002.
            "validate"=>match request_shape(&value,"validate").and_then(|()|model_structure(&value["model"])).and_then(|()|serde_json::from_value::<ValidationRequest>(value).map_err(|e|decode_failure(&e))){Ok(r)if r.operation=="validate"=>match r.model.validate(source_path).map_err(|e|e.in_component("schema")){Ok(v)=>success_response("validate","E2-API-002",serde_json::json!({"config_digest":v.config_digest(),"ir":crate::IR_SCHEMA,"schema_digest":SCHEMA_DIGEST})),Err(e)=>failure_response(operation,e)},Ok(_)=>failure_response(operation,ApiFailure::new(StatusCode::InvalidInput,"E2-API-002")),Err(e)=>failure_response(operation,e)},
            // `E2-API-004` ("MUST be the JSON boolean `true`") and `E2-API-003` (`extension` is an
            // object) are decided on the raw value, before the model, so that a run request with a
            // wrong `allow_unvalidated` is refused "before calculator, output, or checkpoint work"
            // rather than being folded into a decode failure.
            "run"=>match request_shape(&value,"run").and_then(|()|if value["allow_unvalidated"]!=Value::Bool(true){Err(ApiFailure::new(StatusCode::InvalidInput,"E2-API-004"))}else if !value["extension"].is_object(){Err(ApiFailure::new(StatusCode::InvalidInput,"E2-API-003"))}else{model_structure(&value["model"])}).and_then(|()|serde_json::from_value::<RunRequest>(value).map_err(|e|decode_failure(&e))){Ok(r)if r.operation=="run"&&r.allow_unvalidated=>match r.model.validate(source_path).map_err(|e|e.in_component("schema")){Ok(v)=>match v.preflight_run(){Ok(())=>match adapter{Some(a)=>match a.run(&v,&r.extension){Ok(x)if !x.current_state_id.is_empty()&&x.simulation_time_s.is_finite()&&x.simulation_time_s>=0.0&&x.step_index<=MAX_PORTABLE&&x.checkpoint_sequence<=MAX_PORTABLE=>success_response("run","E2-API-003",serde_json::to_value(x).expect("finite run value")),Ok(_)=>failure_response(operation,ApiFailure::new(StatusCode::InternalError,"E2-API-008")),Err(e)=>failure_response(operation,e)},None=>failure_response(operation,ApiFailure::new(StatusCode::CalculatorFailure,"E2-API-003"))},Err(e)=>failure_response(operation,e)},Err(e)=>failure_response(operation,e)},Ok(_)=>failure_response(operation,ApiFailure::new(StatusCode::InvalidInput,"E2-API-004")),Err(e)=>failure_response(operation,e)},
            _=>failure_response(operation,ApiFailure::new(StatusCode::InvalidInput,"E2-API-001")),
        }
    };canonical_json_bytes(&response).unwrap_or_else(|_|b"{\"causal_status\":null,\"context\":{\"component\":\"api\",\"details\":{},\"requirement_id\":\"E2-CAN-001\",\"retryable\":false,\"search_or_event_id\":null,\"state_id\":null},\"exit_code\":70,\"message\":\"internal error\",\"operation\":\"unknown\",\"severity\":\"fatal\",\"status\":\"INTERNAL_ERROR\",\"value\":null}".to_vec())
}
/// `E2-API-001`/`E2-API-002`/`E2-API-003` each fix the exact key set of a request object. The key
/// set is therefore checked on the raw value before any decode, because only there can the failure
/// be attributed to the REQUEST root rather than to a nested model object. `E3-STATUS-002`
/// (normative; adopted by `D-127`) option (a) names the pair `E2-API-001` =>
/// `{required_keys}`, which is what this emits and what the Python backend already emits.
fn request_shape(value:&Value,operation:&str)->Result<(),ApiFailure>{
    let required:&[&str]=match operation{"capabilities"=>&["operation"],"validate"=>&["model","operation"],_=>&["allow_unvalidated","extension","model","operation"]};
    if value.as_object().map_or(false,|m|m.len()==required.len()&&required.iter().all(|k|m.contains_key(*k))){return Ok(())}
    Err(ApiFailure::new(StatusCode::InvalidInput,"E2-API-001").with_detail("required_keys",serde_json::json!(required)))
}
/// `E2-SCOPE-003`: "Unknown keys in every normative object return `INVALID_INPUT`. Only the root
/// model `metadata` object and the run-request `extension` object accept free-form keys."
/// `E3-STATUS-002` fixes the detail schema for this
/// requirement to `{path, unknown}`; the Python backend also reports `missing` from the same test,
/// so all three are emitted. `serde`'s `deny_unknown_fields` cannot say WHICH object was at fault,
/// which is why the key sets are checked here on the raw value instead.
fn object_keys(value:&Value,path:&str,required:&[&str],optional:&[&str])->Result<(),ApiFailure>{
    let at=|f:ApiFailure|f.in_component("schema").with_detail("path",Value::String(path.to_owned()));
    let map=match value.as_object(){Some(m)=>m,None=>return Err(at(ApiFailure::new(StatusCode::InvalidInput,"E2-SCOPE-003")))};
    let mut missing:Vec<&str>=required.iter().copied().filter(|k|!map.contains_key(*k)).collect();
    let mut unknown:Vec<&str>=map.keys().map(String::as_str).filter(|k|!required.contains(k)&&!optional.contains(k)).collect();
    if missing.is_empty()&&unknown.is_empty(){return Ok(())}
    missing.sort();unknown.sort();
    Err(at(ApiFailure::new(StatusCode::InvalidInput,"E2-SCOPE-003")).with_detail("missing",serde_json::json!(missing)).with_detail("unknown",serde_json::json!(unknown)))
}
/// `E2-SCHEMA-001`..`E2-SCHEMA-011` key sets, walked in the order the requirements are written so
/// that the FIRST offending object is the one reported. `E2-SCHEMA-002` is checked between the
/// `$.schema` key set and `$.system`, exactly where `E2-SCHEMA-002` sits in the schema section.
/// Type and range checks stay in `WireModel::validate`; this pass only decides key sets.
fn model_structure(value:&Value)->Result<(),ApiFailure>{
    object_keys(value,"$",&["basin","calculator","discovery","kinetics","output","relaxation","resources","saddle_search","schema","system"],&["metadata"])?;
    object_keys(&value["schema"],"$.schema",&["id"],&[])?;
    if value["schema"]["id"].as_str()!=Some(crate::IR_SCHEMA){return Err(ApiFailure::new(StatusCode::SchemaUnsupported,"E2-SCHEMA-002").in_component("schema"))}
    object_keys(&value["system"],"$.system",&["atom_ids","calculator_model_digest","cell","charge","constraints","movable","pbc","positions","species","spin"],&[])?;
    object_keys(&value["calculator"],"$.calculator",&["deterministic","model_digest","model_name","model_version"],&[])?;
    object_keys(&value["relaxation"],"$.relaxation",&["force_tolerance","max_evaluations","max_steps"],&[])?;
    object_keys(&value["saddle_search"],"$.saddle_search",&["curvature_tolerance","endpoint_displacement","force_tolerance","max_iterations","method","orthogonal_directions"],&[])?;
    object_keys(&value["discovery"],"$.discovery",&["alpha","alpha_calibration","classes","consecutive_redundant","maximum_attempts","maximum_evaluations","minimum_successful","mode","relevance_rate_min"],&[])?;
    if let Some(classes)=value["discovery"]["classes"].as_array(){for(i,c)in classes.iter().enumerate(){object_keys(c,&format!("$.discovery.classes[{i}]"),&["kind","name","probability"],&[])?;}}
    if !value["discovery"]["alpha"].is_null(){object_keys(&value["discovery"]["alpha_calibration"],"$.discovery.alpha_calibration",&["id","source","version"],&[])?;}
    object_keys(&value["kinetics"],"$.kinetics",&["absorbing_ok","barrier_tolerance","detailed_balance_tolerance","log_rate_cutoff","maximum_steps","prefactor","rate_model","run_seed","saddle_energy_tolerance","saddle_max_tolerance","saddle_rms_tolerance","state_energy_tolerance_per_atom","state_max_tolerance","state_rms_tolerance","temperature"],&[])?;
    object_keys(&value["resources"],"$.resources",&["callback_timeout_s","catalog_events","evaluations_per_relaxation","evaluations_per_saddle_attempt","output_bytes","resident_memory_bytes","retry_backoff_s","retry_count","saddle_attempts_per_state","total_calculator_evaluations","wall_time_s"],&[])?;
    object_keys(&value["output"],"$.output",&["checkpoint_every_steps","checkpoint_path","checkpoint_wall_time_s","overwrite","resume","summary_path","trajectory_path"],&[])?;
    object_keys(&value["basin"],"$.basin",&["enabled"],&[])?;
    Ok(())
}
/// A decode failure that survived `model_structure` is a TYPE failure inside a known-shaped object.
/// `E2-SCHEMA-001` is the requirement that fixes those types. `serde` does not carry the JSON path,
/// so `details.path` is not emitted here; the Python backend does emit it, and that residual
/// divergence is recorded rather than papered over.
fn decode_failure(_e:&serde_json::Error)->ApiFailure{ApiFailure::new(StatusCode::InvalidInput,"E2-SCHEMA-001").in_component("schema")}

// `E3-STATUS-001`: every failure below is the JSON reader refusing the
// bytes before any schema work, so the subsystem is `json` (`E2-JSON-001`..`E2-JSON-003`).
fn parse_public(input:&[u8])->Result<Value,ApiFailure>{let json=|s,r|ApiFailure::new(s,r).in_component("json");let text=std::str::from_utf8(input).map_err(|_|json(StatusCode::InvalidInput,"E2-JSON-001"))?;if text.starts_with('\u{feff}'){return Err(json(StatusCode::InvalidInput,"E2-JSON-001"))}if nonfinite_lexeme(text){return Err(json(StatusCode::NonfiniteResult,"E2-JSON-003"))}if portable_integer_violation(text){return Err(json(StatusCode::InvalidInput,"E2-JSON-002"))}parse_strict_json(input).map_err(|_|json(StatusCode::InvalidInput,"E2-JSON-001"))}
fn nonfinite_lexeme(s:&str)->bool{let mut string=false;let mut escape=false;let chars:Vec<char>=s.chars().collect();let mut visible=String::new();for c in chars{if string{if escape{escape=false}else if c=='\\'{escape=true}else if c=='"'{string=false}}else if c=='"'{string=true}else{visible.push(c)}}if visible.split(|c:char|c.is_whitespace()||"[]{},:".contains(c)).any(|t|matches!(t,"NaN"|"Infinity"|"-Infinity")){return true}visible.split(|c:char|c.is_whitespace()||"[]{},:".contains(c)).filter(|t|t.contains('.')||t.contains('e')||t.contains('E')).any(|t|t.parse::<f64>().map_or(false,|x|!x.is_finite()))}
fn success_response(operation:&str,requirement:&str,value:Value)->ApiResponse{ApiResponse{causal_status:None,context:ApiContext{component:"api".into(),details:Map::new(),requirement_id:requirement.into(),retryable:false,search_or_event_id:None,state_id:None},exit_code:0,message:"transaction committed".into(),operation:operation.into(),severity:Severity::Success,status:StatusCode::Ok,value:Some(value)}}
fn failure_response(operation:String,e:ApiFailure)->ApiResponse{let(original,mut causal)=(e.status,e.causal_status);let status=if original.exit_code(false,false).is_none(){causal=Some(original);StatusCode::InternalError}else{original};let exit=status.exit_code(false,false).expect("public terminal status has exit code");ApiResponse{causal_status:causal,context:ApiContext{component:e.component,details:e.details,requirement_id:e.requirement_id,retryable:false,search_or_event_id:None,state_id:None},exit_code:exit,message:stable_message(status).into(),operation,severity:status.severity(),status,value:None}}
fn capability_value()->Value{serde_json::json!({"api":JSON_API,"basin_acceleration":"disabled","conformance":"unvalidated","features":{"common_prefactor":true,"deterministic_checkpoint":true,"fixed_composition_off_lattice":true,"harmonic_tst":false,"local_environment_generic_reuse":false,"serial_kmc":true,"variable_composition":false},"ir":crate::IR_SCHEMA,"operations":["capabilities","validate","run"],"production":false,"release":false,"validated":false})}
pub fn stable_message(s:StatusCode)->&'static str{use StatusCode::*;match s{Ok=>"transaction committed",DiscoveryConvergedHeuristic=>"heuristic discovery criterion passed",DuplicateEvent=>"duplicate event rejected",SaddleNotFound=>"saddle not found",InvalidSaddle=>"saddle validation failed",SaddleWrongBasin=>"neither endpoint matches origin",EndpointCollapsed=>"both endpoints match origin",EnvironmentAmbiguous=>"environment identity ambiguous",BasinDisabled=>"basin acceleration disabled",DiscoveryIncomplete=>"discovery budget exhausted",RelaxNotConverged=>"relaxation not converged",EventApplicationFailed=>"event application failed",CalculatorFailure=>"calculator callback failed",NonfiniteResult=>"nonfinite value rejected",InvalidInput=>"input invalid",SchemaUnsupported=>"schema unsupported",InvalidState=>"state invalid",RateInvalid=>"rate invalid",DetailedBalanceViolation=>"detailed balance violated",CatalogConflict=>"catalog conflict",CatalogIncompatible=>"catalog incompatible",AtomCountChangeUnsupported=>"atom count change unsupported",NoEnabledEvent=>"no enabled event",ResourceLimit=>"resource limit reached",OutputExists=>"output exists",CheckpointCorrupt=>"checkpoint corrupt",CheckpointIncompatible=>"checkpoint incompatible",Cancelled=>"run cancelled",InternalError=>"internal error"}}

pub fn trajectory_stream(run_seed:u64)->crate::rng::Philox{crate::rng::derive_trajectory_stream(run_seed)}
pub fn saddle_stream(run_seed:u64,state_id:&str,class:&str,index:u64)->Result<crate::rng::Philox,ApiFailure>{crate::rng::derive_saddle_substream(run_seed,state_id,class,index).map_err(|_|ApiFailure::new(StatusCode::InvalidInput,"E2-RNG-004"))}
pub fn search_id(run_seed:u64,state_id:&str,class:&str,index:u64)->Result<String,ApiFailure>{let v=serde_json::json!({"run_seed":run_seed,"search_class":class,"search_index":index,"state_id":state_id});Ok(format!("search:sha256:{}",hex_sha256(&canonical_json_bytes(&v).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-DISC-002"))?)))}

pub fn geometry_certificate(system:&WireSystem)->Result<Value,ApiFailure>{let mut anchors=Vec::new();for a in 0..system.positions.len(){let mut rows=Vec::new();for j in 0..system.positions.len(){let delta=[system.positions[j][0]-system.positions[a][0],system.positions[j][1]-system.positions[a][1],system.positions[j][2]-system.positions[a][2]];let v=closest_periodic_vector(delta,system.cell,system.pbc,1_000_000,1e-12).map_err(|_|ApiFailure::new(StatusCode::InvalidState,"E2-ID-002"))?.displacement;rows.push(serde_json::json!([system.species[j],system.movable[j],v[0],v[1],v[2]]));}rows.sort_by(|x,y|canonical_json_bytes(x).expect("finite row").cmp(&canonical_json_bytes(y).expect("finite row")));anchors.push(serde_json::json!({"cell":system.cell,"pbc":system.pbc,"rows":rows,"version":"anchor-minimum-closest-image/1"}));}anchors.into_iter().min_by(|x,y|canonical_json_bytes(x).expect("finite certificate").cmp(&canonical_json_bytes(y).expect("finite certificate"))).ok_or_else(||ApiFailure::new(StatusCode::InvalidState,"E2-ID-002"))}
pub fn fixed_contract_digest(system:&WireSystem)->Result<String,ApiFailure>{let mut contracts:Vec<Value>=system.species.iter().zip(&system.movable).map(|(s,m)|serde_json::json!([s,m])).collect();contracts.sort_by(|x,y|canonical_json_bytes(x).expect("finite contract").cmp(&canonical_json_bytes(y).expect("finite contract")));digest_value(&serde_json::json!({"atom_contracts":contracts,"calculator_model_digest":system.calculator_model_digest,"cell":system.cell,"charge":system.charge,"constraints":system.constraints,"pbc":system.pbc,"spin":system.spin}))}
pub fn constraint_digest(system:&WireSystem)->Result<String,ApiFailure>{digest_value(&serde_json::json!({"constraints":system.constraints,"movable":system.movable}))}
pub fn state_ids(system:&WireSystem,energy:f64)->Result<(String,String),ApiFailure>{if !energy.is_finite(){return Err(ApiFailure::new(StatusCode::NonfiniteResult,"E2-ID-004"))}let fixed=fixed_contract_digest(system)?;let candidate=format!("candidate:sha256:{}",hex_sha256(&canonical_json_bytes(&serde_json::json!({"fixed_contract_digest":fixed,"geometry":geometry_certificate(system)?,"version":IDENTITY_VERSION_V2})).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-ID-004"))?));let state=format!("state:sha256:{}",hex_sha256(&canonical_json_bytes(&serde_json::json!({"candidate_identity":candidate,"energy_ev":energy,"fixed_contract_digest":fixed,"version":IDENTITY_VERSION_V2})).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-ID-004"))?));Ok((candidate,state))}

#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct RelaxationProvenanceV2{pub calculator_evaluations:u64,pub calculator_identity:String,pub minimizer_identity:String,pub steps:u64,pub termination_reason:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CommittedStateV2{pub atom_ids:Vec<String>,pub calculator_model_digest:String,pub candidate_identity:String,pub cell:Cell,pub charge:f64,pub constraint_digest:String,pub constraints:WireConstraints,pub energy_ev:f64,pub fixed_contract_digest:String,pub force_tolerance_ev_per_angstrom:f64,pub forces_ev_per_angstrom:Vec<Vec3>,pub identity_version:String,pub max_movable_force_ev_per_angstrom:f64,pub movable:Vec<bool>,pub pbc:[bool;3],pub positions:Vec<Vec3>,pub relaxation_provenance:RelaxationProvenanceV2,pub schema:String,pub species:Vec<String>,pub spin:f64,pub state_id:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct MatchV2{pub atom_mapping:Vec<usize>,pub energy_difference_ev:f64,pub max_displacement_angstrom:f64,pub rms_displacement_angstrom:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct SaddleV2{pub curvature_ev_per_angstrom2:f64,pub energy_ev:f64,pub evaluation_count:u64,pub evidence_level:String,pub forces_ev_per_angstrom:Vec<Vec3>,pub orthogonal_curvatures_ev_per_angstrom2:Vec<f64>,pub positions:Vec<Vec3>,pub search_id:String,pub termination_reason:String,pub unstable_direction:Vec<Vec3>}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct RateModelV2{pub common_prefactor_per_s:f64,pub detailed_balance_residual:f64,pub log_forward_rate_per_s:f64,pub log_reverse_rate_per_s:f64,pub model:String,pub temperature_k:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct DiscoveryProvenanceV2{pub rng_substream_digest:String,pub search_class:String,pub search_id:String,pub search_index:u64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct EventValidationV2{pub calculator_model_digest:String,pub constraint_digest:String,pub destination_match:MatchV2,pub full_endpoint_relaxations:bool,pub method:String,pub origin_match:MatchV2,pub unstable_mode_count:u64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct DirectedEventV2{pub schema:String,pub event_id:String,pub reverse_event_id:String,pub pair_id:String,pub origin_state_id:String,pub destination_state_id:String,pub saddle:SaddleV2,pub barrier_ev:f64,pub reverse_barrier_ev:f64,pub rate_model:RateModelV2,pub selectable:bool,pub active_atom_mapping:Vec<[usize;2]>,pub environment_key:String,pub environment_version:String,pub discovery_provenance:DiscoveryProvenanceV2,pub validation:EventValidationV2,pub calculator_digest:String,pub identity_digest:String,pub schema_digest:String,pub tolerance_digest:String}
pub fn event_ids(origin:&str,destination:&str,saddle:&SaddleV2,saddle_geometry_digest:&str,mapping:&[[usize;2]])->Result<(String,String,String),ApiFailure>{let mut endpoints=[origin,destination];endpoints.sort();let mut oriented=mapping.to_vec();if origin>endpoints[0]{oriented=oriented.into_iter().map(|x|[x[1],x[0]]).collect()}oriented.sort();let flat:Vec<f64>=saddle.unstable_direction.iter().flatten().copied().collect();let neg:Vec<f64>=flat.iter().map(|x|-x).collect();let direction=if canonical_json_bytes(&flat).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-EVENT-006"))?<=canonical_json_bytes(&neg).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-EVENT-006"))?{flat}else{neg};let pair=format!("pair:sha256:{}",hex_sha256(&canonical_json_bytes(&serde_json::json!({"active_atom_mapping":oriented,"endpoint_state_ids":endpoints,"saddle_energy_ev":saddle.energy_ev,"saddle_geometry_digest":saddle_geometry_digest,"schema":"spark-atomistic-event-pair/2","unstable_direction":direction})).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-EVENT-006"))?));let one=|a:&str,b:&str|->Result<String,ApiFailure>{Ok(format!("event:sha256:{}",hex_sha256(&canonical_json_bytes(&serde_json::json!({"destination_state_id":b,"origin_state_id":a,"pair_id":pair,"schema":"spark-atomistic-directed-event/2"})).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-EVENT-006"))?)))};Ok((pair.clone(),one(origin,destination)?,one(destination,origin)?))}

#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct RateTablePayload{pub destination_state_ids:Vec<String>,pub event_ids:Vec<String>,pub log_rates:Vec<f64>,pub lost_rate_log_upper_bound:Option<f64>,pub origin_state_id:String,pub rates:Vec<f64>,pub schema:String,pub total_rate_per_s:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct RateTableSnapshot{pub payload:RateTablePayload,pub payload_sha256:String}
impl RateTableSnapshot{pub fn new(payload:RateTablePayload)->Result<Self,ApiFailure>{let n=payload.event_ids.len();if payload.schema!="spark-atomistic-rate-table-snapshot/1"||payload.origin_state_id.is_empty()||n==0||n!=payload.rates.len()||n!=payload.log_rates.len()||n!=payload.destination_state_ids.len()||payload.event_ids.windows(2).any(|w|w[0]>=w[1])||payload.event_ids.iter().chain(&payload.destination_state_ids).any(String::is_empty)||payload.rates.iter().any(|x|!x.is_finite()||*x<=0.0)||payload.log_rates.iter().any(|x|!x.is_finite())||payload.rates.iter().zip(&payload.log_rates).any(|(r,l)|r.to_bits()!=l.exp().to_bits())||payload.lost_rate_log_upper_bound.map_or(false,|x|!x.is_finite()){return Err(ApiFailure::new(StatusCode::RateInvalid,"E2-KMC-002"))}let total=crate::rate::neumaier_sum(&payload.rates).map_err(|_|ApiFailure::new(StatusCode::RateInvalid,"E2-KMC-002"))?;if total.to_bits()!=payload.total_rate_per_s.to_bits(){return Err(ApiFailure::new(StatusCode::RateInvalid,"E2-KMC-002"))}let hash=digest_value(&serde_json::to_value(&payload).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-KMC-002"))?)?;Ok(Self{payload,payload_sha256:hash})}pub fn validate(&self)->Result<(),ApiFailure>{let expected=Self::new(self.payload.clone())?;if expected.payload_sha256!=self.payload_sha256{return Err(ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-KMC-005"))}Ok(())}}
pub fn make_rate_snapshot(origin:&str,rows:&[(String,String,f64)],cutoff:f64)->Result<RateTableSnapshot,ApiFailure>{if origin.is_empty()||!cutoff.is_finite(){return Err(ApiFailure::new(StatusCode::RateInvalid,"E2-RATE-002"))}let mut sorted=rows.to_vec();sorted.sort_by(|a,b|a.0.cmp(&b.0));if sorted.windows(2).any(|w|w[0].0==w[1].0){return Err(ApiFailure::new(StatusCode::RateInvalid,"E2-KMC-002"))}let mut ids=Vec::new();let mut destinations=Vec::new();let mut logs=Vec::new();let mut rates=Vec::new();let mut lost=Vec::new();for(id,destination,log)in sorted{if id.is_empty()||destination.is_empty()||!log.is_finite(){return Err(ApiFailure::new(StatusCode::RateInvalid,"E2-RATE-002"))}if log>=cutoff{let rate=log.exp();if !rate.is_finite()||rate<=0.0{return Err(ApiFailure::new(StatusCode::RateInvalid,"E2-RATE-002"))}ids.push(id);destinations.push(destination);logs.push(log);rates.push(rate)}else{lost.push(log)}}if ids.is_empty(){return Err(ApiFailure::new(StatusCode::NoEnabledEvent,"E2-KMC-001"))}let total=crate::rate::neumaier_sum(&rates).map_err(|_|ApiFailure::new(StatusCode::RateInvalid,"E2-KMC-001"))?;let lost_rate_log_upper_bound=if lost.is_empty(){None}else{Some(crate::rate::log_sum_exp(&lost).map_err(|_|ApiFailure::new(StatusCode::RateInvalid,"E2-RATE-002"))?)};RateTableSnapshot::new(RateTablePayload{destination_state_ids:destinations,event_ids:ids,log_rates:logs,lost_rate_log_upper_bound,origin_state_id:origin.into(),rates,schema:"spark-atomistic-rate-table-snapshot/1".into(),total_rate_per_s:total})}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct KmcStepV2{pub checkpoint_sequence:u64,pub log_sequence:u64,pub post_state_id:String,pub pre_state_id:String,pub rate_table_snapshot:RateTableSnapshot,pub selected_event_id:String,pub selected_rate_per_s:f64,pub selection_uniform:f64,pub step_index:u64,pub time_increment_s:f64,pub time_uniform:f64,pub total_rate_per_s:f64}

#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(untagged)]pub enum ConfidenceV2{Number(f64),Unavailable(String)}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct DiscoveryStatsV2{pub alpha:Option<f64>,pub alpha_calibration:Option<WireCalibration>,pub attempts:u64,pub config_digest:String,pub consecutive_redundant_successes:u64,pub duplicates:u64,pub evaluations:u64,pub event_log_rates:BTreeMap<String,f64>,pub failures_by_status:BTreeMap<StatusCode,u64>,pub heuristic_confidence:ConfidenceV2,pub permanently_incomplete_catalog:bool,pub relevance_rate_min:f64,pub state_id:String,pub stopping_state:String,pub successes:u64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CheckpointDigestsV2{pub config:String,pub model:String,pub schema:String,pub tolerances:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CheckpointRngV2{pub run_seed:u64,pub substream_map:BTreeMap<String,PhiloxState>,pub trajectory:PhiloxState}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct BasinCheckpointV2{pub enabled:bool,pub reason:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CheckpointFlagsV2{pub cancelled:bool,pub complete:bool,pub incomplete_catalog:bool,pub last_status:StatusCode,pub resource_limited:bool}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CheckpointResourcesV2{pub calculator_evaluations:u64,pub catalog_events:u64,pub output_bytes:u64,pub resident_memory_bytes:u64,pub retry_history:Vec<Value>,pub saddle_attempts_by_state:BTreeMap<String,u64>,pub wall_elapsed_s:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CatalogV2{pub digest:String,pub events:BTreeMap<String,DirectedEventV2>,pub multiplicity:BTreeMap<String,u64>,pub schema:String,pub states:BTreeMap<String,CommittedStateV2>}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CheckpointPayloadV2{pub basin:BasinCheckpointV2,pub catalog:CatalogV2,pub checkpoint_sequence:u64,pub digests:CheckpointDigestsV2,pub discovery_statistics:BTreeMap<String,DiscoveryStatsV2>,pub flags:CheckpointFlagsV2,pub initial_state:CommittedStateV2,pub log_sequence:u64,pub resources:CheckpointResourcesV2,pub rng:CheckpointRngV2,pub schema:String,pub simulation_time_s:f64,pub step_index:u64,pub trajectory:Vec<KmcStepV2>,pub current_state:CommittedStateV2}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(deny_unknown_fields)]pub struct CheckpointEnvelopeV2{pub payload:CheckpointPayloadV2,pub payload_sha256:String,
    /// Which of the two hash rules below this envelope's `payload_sha256` was sealed under. Not on
    /// the wire: `E2-CKPT-001` fixes the envelope to exactly `payload` and `payload_sha256`.
    #[serde(skip)]pub sealed_with:PayloadHashPolicy}

/// `E3-PAR-002` (normative; adopted by `D-127`). `E2-CKPT-005` makes
/// `resources.wall_elapsed_s` mandatory and `E2-PAR-003` demands byte identity. Measured on this
/// backend: two consecutive runs of the SAME input in the same directory both produced 5439 bytes
/// that differed at offset 4909 (`0.353757169` vs `0.355789421`), which changes `payload_sha256`.
/// The two requirements are therefore jointly unsatisfiable even against oneself. The proposal's
/// recommended resolution -- keep the field in the record, exclude environment-derived fields from
/// the HASHED payload -- is implemented as `Errata3EnvironmentExcluded`; `PreErrata3Full` keeps
/// `E2-CKPT-001` as literally written and stays accepted on read, because the mandatory
/// `E2-PAR-002`(10) clean-checkpoint fixture was sealed under it by the other backend.
#[derive(Clone,Copy,Debug,PartialEq,Eq,Default)]pub enum PayloadHashPolicy{
    /// `E2-CKPT-001`: "The hash covers canonical payload bytes." Every byte, including wall clock.
    PreErrata3Full,
    /// `E3-PAR-002`: every byte EXCEPT the declared environment-derived
    /// set below, so two runs of the same input on the same host agree on `payload_sha256`.
    #[default] Errata3EnvironmentExcluded,
}
/// The declared environment-derived set, as `(payload object, field)`. It is exactly the fields of
/// this backend whose value is read from the host rather than computed from the model and the
/// committed work. `resources.resident_memory_bytes` is NOT in it: in this backend that counter is
/// a deterministic ledger reservation (`src/resource.rs`), not a host measurement, so excluding it
/// would hide real corruption.
pub const ENVIRONMENT_DERIVED_PAYLOAD_FIELDS:&[(&str,&str)]=&[("resources","wall_elapsed_s")];
/// Reserve every checkpoint as if its canonical `wall_elapsed_s` token occupied the maximum
/// finite-binary64 width. The ledger therefore never undercounts physical bytes, while the
/// cumulative `resources.output_bytes` value cannot inherit wall-clock token-length jitter.
const MAX_CANONICAL_FINITE_F64_BYTES:usize=24;
fn normalized_checkpoint_reservation(encoded_len:usize,wall_elapsed_s:f64)->Result<u64,ApiFailure>{
    if !wall_elapsed_s.is_finite()||wall_elapsed_s<0.0{return Err(ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-005"))}
    let token_len=canonical_json_bytes(&serde_json::json!(wall_elapsed_s)).map_err(|_|ApiFailure::new(StatusCode::NonfiniteResult,"E2-CAN-004"))?.len();
    let padding=MAX_CANONICAL_FINITE_F64_BYTES.checked_sub(token_len).ok_or_else(||ApiFailure::new(StatusCode::InternalError,"E2-CKPT-009"))?;
    encoded_len.checked_add(padding).and_then(|n|u64::try_from(n).ok()).ok_or_else(||ApiFailure::new(StatusCode::ResourceLimit,"E2-CKPT-009"))
}
fn hashed_payload_value(payload:&CheckpointPayloadV2,policy:PayloadHashPolicy)->Result<Value,ApiFailure>{
    let mut value=serde_json::to_value(payload).map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-CKPT-001"))?;
    if policy==PayloadHashPolicy::Errata3EnvironmentExcluded{
        for(object,field)in ENVIRONMENT_DERIVED_PAYLOAD_FIELDS{
            if let Some(m)=value.get_mut(*object).and_then(Value::as_object_mut){m.remove(*field);}
        }
    }
    Ok(value)
}
impl CheckpointEnvelopeV2{pub fn new(payload:CheckpointPayloadV2)->Result<Self,ApiFailure>{Self::new_sealed(payload,PayloadHashPolicy::default())}
pub fn new_sealed(payload:CheckpointPayloadV2,sealed_with:PayloadHashPolicy)->Result<Self,ApiFailure>{let payload_sha256=digest_value(&hashed_payload_value(&payload,sealed_with)?)?;Ok(Self{payload,payload_sha256,sealed_with})}
/// The seal under which `stored` was produced, or `None` when it matches neither rule. The two
/// digests can never coincide, because `resources.wall_elapsed_s` is mandatory (`E2-CKPT-005`) and
/// so is always present to remove, which makes the classification unambiguous.
pub fn detect_seal(payload:&CheckpointPayloadV2,stored:&str)->Option<PayloadHashPolicy>{
    for policy in [PayloadHashPolicy::Errata3EnvironmentExcluded,PayloadHashPolicy::PreErrata3Full]{
        if hashed_payload_value(payload,policy).and_then(|v|digest_value(&v)).map_or(false,|d|d==stored){return Some(policy)}
    }
    None
}
pub fn validate_envelope(&self,expected:&CheckpointDigestsV2)->Result<(),ApiFailure>{if Self::detect_seal(&self.payload,&self.payload_sha256)!=Some(self.sealed_with){return Err(ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-001"))}if &self.payload.digests!=expected{return Err(ApiFailure::new(StatusCode::CheckpointIncompatible,"E2-CKPT-007"))}if self.payload.schema!="spark-atomistic-checkpoint/2"||self.payload.basin!=(BasinCheckpointV2{enabled:false,reason:"v1-disabled".into()})||self.payload.catalog.schema!="spark-atomistic-catalog/2"||self.payload.step_index!=self.payload.trajectory.len()as u64||self.payload.log_sequence!=self.payload.step_index||self.payload.rng.trajectory.consumed_uniforms!=self.payload.step_index.saturating_mul(2)||!self.payload.resources.retry_history.is_empty(){return Err(ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-007"))}for step in &self.payload.trajectory{step.rate_table_snapshot.validate()?;}Ok(())}}

pub fn decode_checkpoint_v2(bytes:&[u8],expected:&ValidatedModel)->Result<CheckpointEnvelopeV2,ApiFailure>{decode_checkpoint_v2_with(bytes,expected,CheckpointPolicy::default())}
pub fn decode_checkpoint_v2_with(bytes:&[u8],expected:&ValidatedModel,policy:CheckpointPolicy)->Result<CheckpointEnvelopeV2,ApiFailure>{let value=parse_strict_json(bytes).map_err(|_|ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-007"))?;let canonical=canonical_json_bytes(&value).map_err(|_|ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-007"))?;if canonical!=bytes{return Err(ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-007"))}let mut envelope:CheckpointEnvelopeV2=serde_json::from_value(value).map_err(|_|ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-001"))?;
    // `E2-CKPT-007`(2) verifies the payload SHA-256. Both hash rules are accepted on read and the
    // one that matched is carried on the envelope, so a re-encode reproduces the input bytes rather
    // than resealing them under a different rule (`E3-PAR-002`).
    envelope.sealed_with=CheckpointEnvelopeV2::detect_seal(&envelope.payload,&envelope.payload_sha256).ok_or_else(||ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-001"))?;let digests=CheckpointDigestsV2{config:expected.config_digest.clone(),model:expected.model.calculator.model_digest.clone(),schema:SCHEMA_DIGEST.into(),tolerances:expected.tolerance_digest.clone()};envelope.validate_envelope(&digests)?;validate_checkpoint_v2_with(&envelope.payload,expected,policy)?;Ok(envelope)}
pub fn encode_checkpoint_v2(payload:CheckpointPayloadV2,expected:&ValidatedModel)->Result<Vec<u8>,ApiFailure>{encode_checkpoint_v2_with(payload,expected,CheckpointPolicy::default())}
pub fn encode_checkpoint_v2_with(payload:CheckpointPayloadV2,expected:&ValidatedModel,policy:CheckpointPolicy)->Result<Vec<u8>,ApiFailure>{encode_checkpoint_v2_sealed(payload,expected,policy,PayloadHashPolicy::default())}
pub fn encode_checkpoint_v2_sealed(payload:CheckpointPayloadV2,expected:&ValidatedModel,policy:CheckpointPolicy,seal:PayloadHashPolicy)->Result<Vec<u8>,ApiFailure>{let envelope=CheckpointEnvelopeV2::new_sealed(payload,seal)?;let digests=CheckpointDigestsV2{config:expected.config_digest.clone(),model:expected.model.calculator.model_digest.clone(),schema:SCHEMA_DIGEST.into(),tolerances:expected.tolerance_digest.clone()};envelope.validate_envelope(&digests)?;validate_checkpoint_v2_with(&envelope.payload,expected,policy)?;canonical_json_bytes(&envelope).map_err(|_|ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-001"))}
static E2_TEMP_SEQUENCE:AtomicU64=AtomicU64::new(0);
pub fn write_checkpoint_v2(path:&Path,payload:CheckpointPayloadV2,expected:&ValidatedModel,has_valid_checkpoint:bool,ledger:&mut crate::resource::ResourceLedger)->Result<(),ApiFailure>{
    let wall_elapsed_s=payload.resources.wall_elapsed_s;let bytes=encode_checkpoint_v2(payload,expected)?;let parent=path.parent().ok_or_else(||ApiFailure::new(StatusCode::InvalidInput,"E2-CKPT-009"))?;let name=path.file_name().and_then(|x|x.to_str()).ok_or_else(||ApiFailure::new(StatusCode::InvalidInput,"E2-CKPT-009"))?;let reserved=normalized_checkpoint_reservation(bytes.len(),wall_elapsed_s)?;ledger.reserve_output(reserved).map_err(|_|ApiFailure::new(StatusCode::ResourceLimit,"E2-CKPT-009"))?;
    let mut opened=None;for _ in 0..16{let seq=E2_TEMP_SEQUENCE.fetch_add(1,Ordering::SeqCst);let temp=parent.join(format!(".{name}.tmp.{}.{}",std::process::id(),seq));match OpenOptions::new().write(true).create_new(true).open(&temp){Ok(file)=>{opened=Some((temp,file));break},Err(e)if e.kind()==std::io::ErrorKind::AlreadyExists=>{},Err(_)=>break}}
    let(temp,mut file)=match opened{Some(x)=>x,None=>{let _=ledger.refund_output(reserved);return Err(ApiFailure::new(if has_valid_checkpoint{StatusCode::ResourceLimit}else{StatusCode::CheckpointCorrupt},"E2-CKPT-009"))}};let mut renamed=false;let result=(||->std::io::Result<()>{file.write_all(&bytes)?;file.sync_all()?;fs::rename(&temp,path)?;renamed=true;File::open(parent)?.sync_all()?;Ok(())})();
    if let Err(e)=result{let mut failure=ApiFailure::new(if has_valid_checkpoint{StatusCode::ResourceLimit}else{StatusCode::CheckpointCorrupt},"E2-CKPT-009");failure.details.insert("io_error".into(),Value::String(e.to_string()));if renamed{failure.details.insert("cleanup_reason".into(),Value::String("destination retained after parent-directory flush failure".into()));}else{let cleanup=fs::remove_file(&temp).map(|_|"temporary checkpoint removed".to_owned()).unwrap_or_else(|x|format!("temporary checkpoint retained: {x}"));failure.details.insert("cleanup_reason".into(),Value::String(cleanup));let _=ledger.refund_output(reserved);}return Err(failure)}Ok(())
}
/// `E3-EVENT-001` (normative; adopted by `D-127`). The Errata-2 text
/// leaves three checkpoint invariants unstated, and this backend enforced all three at once:
///   C1 `saddle.search_id == discovery_provenance.search_id`  -- in no requirement,
///   C2 `reverse.saddle == event.saddle`                      -- in no requirement,
///   C3 each record's provenance re-derives from ITS OWN `origin_state_id` -- `E2-DISC-002` binds
///      the search ID to *a* state, not to each record's origin.
/// C1+C2 force one search ID per pair and C3 forces two, while `E2-EVENT-001` ("`origin_state_id`,
/// `destination_state_id` | Distinct committed IDs") forbids collapsing the endpoints, so every
/// reciprocal pair was refused and `run` could not return `OK` for any model that discovers an
/// event. `Errata3Event001` implements the proposal's recommended options 1 + 4; `PreErrata3`
/// keeps the shipped behaviour reachable so the difference stays measurable and revertible.
#[derive(Clone,Copy,Debug,PartialEq,Eq,Default)]pub enum CheckpointPolicy{
    /// Behaviour before Errata 3: C1 + C2 (byte equality) + C3, `validation.method` forced to equal
    /// `saddle.evidence_level`, and `discovery_statistics.config_digest` = digest of `discovery`.
    PreErrata3,
    /// `E3-EVENT-001` options 1 + 4: C3 dropped for "the search ID
    /// re-derives from exactly one of {origin, destination} and both records carry an identical
    /// `discovery_provenance`"; C2 relaxed to mapped equality.
    #[default] Errata3Event001,
}

/// `E3-EVENT-001` option 4: "Reciprocal saddle = forward saddle mapped
/// through `validation.destination_match.atom_mapping` with `unstable_direction` negated."
/// `E2-EVENT-005` fixes `destination_match.atom_mapping`; it is read from the record under
/// inspection, so the relation is asserted once from each side of the pair and a pair whose two
/// mappings are not inverses is refused rather than silently accepted.
pub fn mapped_saddle(forward:&SaddleV2,mapping:&[usize])->Option<SaddleV2>{
    let n=forward.positions.len();
    if mapping.len()!=n||forward.forces_ev_per_angstrom.len()!=n||forward.unstable_direction.len()!=n{return None}
    let mut seen=vec![false;n];
    for m in mapping{if *m>=n||seen[*m]{return None}seen[*m]=true}
    let mut out=forward.clone();
    for i in 0..n{
        out.positions[mapping[i]]=forward.positions[i];
        out.forces_ev_per_angstrom[mapping[i]]=forward.forces_ev_per_angstrom[i];
        let v=forward.unstable_direction[i];out.unstable_direction[mapping[i]]=[-v[0],-v[1],-v[2]];
    }
    Some(out)
}
/// `E2-DISC-002`: "Search ID hashes exactly `{"run_seed":seed,"search_class":name,
/// "search_index":index,"state_id":state_id}`". It binds the ID to *a* state and never says that
/// the state is each record's own origin. `E3-EVENT-001` option 1 reads it
/// as the DISCOVERING state, which is the origin on the forward record and the destination on the
/// reciprocal one; `E2-EVENT-001` ("Distinct committed IDs") makes "exactly one of {origin,
/// destination}" well defined, and the ambiguous case is refused explicitly rather than assumed away.
fn discovering_state(p:&CheckpointPayloadV2,event:&DirectedEventV2,policy:CheckpointPolicy)->Result<String,ApiFailure>{
    let fail=||ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-007");
    let prov=&event.discovery_provenance;
    let derives=|state:&str|->Result<bool,ApiFailure>{Ok(search_id(p.rng.run_seed,state,&prov.search_class,prov.search_index).map_err(|_|fail())?==prov.search_id)};
    if policy==CheckpointPolicy::PreErrata3{
        if !derives(&event.origin_state_id)?{return Err(fail())}
        return Ok(event.origin_state_id.clone());
    }
    let mut found:Option<String>=None;
    for endpoint in [&event.origin_state_id,&event.destination_state_id]{
        if derives(endpoint)?{if found.is_some(){return Err(fail())}found=Some(endpoint.clone())}
    }
    let discovering=found.ok_or_else(fail)?;
    // Option 1 also states that BOTH records of the pair carry an identical `discovery_provenance`.
    let reverse=p.catalog.events.get(&event.reverse_event_id).ok_or_else(fail)?;
    if reverse.discovery_provenance!=*prov{return Err(fail())}
    Ok(discovering)
}
/// `E2-DISC-004` names `discovery_statistics[*].config_digest` but not WHICH config it digests.
/// `E2-CAN-007` is the only definition of the term in the erratum -- "`config_digest` hashes the
/// complete validated model after removing root `metadata`" -- so under `E3-EVENT-001` that is the
/// binding checked here, which is also what the Python backend stores. `PreErrata3` keeps the
/// shipped reading (the digest of the `discovery` object alone) reachable.
fn discovery_config_binding<'a>(expected:&'a ValidatedModel,policy:CheckpointPolicy)->&'a str{
    match policy{CheckpointPolicy::PreErrata3=>expected.discovery_config_digest(),CheckpointPolicy::Errata3Event001=>expected.config_digest()}
}
fn reciprocal_saddle_ok(event:&DirectedEventV2,reverse:&DirectedEventV2,policy:CheckpointPolicy)->bool{
    match policy{
        CheckpointPolicy::PreErrata3=>reverse.saddle==event.saddle,
        CheckpointPolicy::Errata3Event001=>mapped_saddle(&event.saddle,&event.validation.destination_match.atom_mapping).map_or(false,|x|x==reverse.saddle),
    }
}
pub fn validate_checkpoint_v2(p:&CheckpointPayloadV2,expected:&ValidatedModel)->Result<(),ApiFailure>{validate_checkpoint_v2_with(p,expected,CheckpointPolicy::default())}
fn validate_checkpoint_v2_with(p:&CheckpointPayloadV2,expected:&ValidatedModel,policy:CheckpointPolicy)->Result<(),ApiFailure>{let fail=||ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-CKPT-007");let mut catalog_value=serde_json::to_value(&p.catalog).map_err(|_|fail())?;catalog_value.as_object_mut().ok_or_else(fail)?.remove("digest");if digest_value(&catalog_value)?!=p.catalog.digest||p.catalog.multiplicity.iter().any(|(id,n)|*n==0||!p.catalog.events.contains_key(id)){return Err(fail())}for(id,state)in &p.catalog.states{validate_state_v2(state)?;if id!=&state.state_id{return Err(fail())}}if p.catalog.states.get(&p.initial_state.state_id)!=Some(&p.initial_state)||p.catalog.states.get(&p.current_state.state_id)!=Some(&p.current_state){return Err(fail())}for(id,event)in &p.catalog.events{validate_event_v2(event,&p.catalog.states,expected,policy)?;if id!=&event.event_id{return Err(fail())}let reverse=p.catalog.events.get(&event.reverse_event_id).ok_or_else(fail)?;let mut reverse_mapping:Vec<[usize;2]>=event.active_atom_mapping.iter().map(|x|[x[1],x[0]]).collect();reverse_mapping.sort();if reverse.reverse_event_id!=event.event_id||reverse.pair_id!=event.pair_id||reverse.origin_state_id!=event.destination_state_id||reverse.destination_state_id!=event.origin_state_id||!reciprocal_saddle_ok(event,reverse,policy)||reverse.barrier_ev.to_bits()!=event.reverse_barrier_ev.to_bits()||reverse.reverse_barrier_ev.to_bits()!=event.barrier_ev.to_bits()||reverse.rate_model.log_forward_rate_per_s.to_bits()!=event.rate_model.log_reverse_rate_per_s.to_bits()||reverse.rate_model.log_reverse_rate_per_s.to_bits()!=event.rate_model.log_forward_rate_per_s.to_bits()||reverse.rate_model.detailed_balance_residual.to_bits()!=(-event.rate_model.detailed_balance_residual).to_bits()||reverse.active_atom_mapping!=reverse_mapping{return Err(fail())}}
    for(id,d)in &p.discovery_statistics{if id!=&d.state_id||d.config_digest!=discovery_config_binding(expected,policy)||!matches!(d.stopping_state.as_str(),"RUNNING"|"CONVERGED_HEURISTIC"|"INCOMPLETE")||d.successes.checked_add(d.failures_by_status.values().sum()).map_or(true,|x|x!=d.attempts)||d.duplicates>d.successes||d.consecutive_redundant_successes>d.duplicates||d.event_log_rates.keys().any(|e|!p.catalog.events.contains_key(e)){return Err(fail())}match &d.heuristic_confidence{ConfidenceV2::Number(x)if x.is_finite()=>{},ConfidenceV2::Unavailable(x)if x=="UNAVAILABLE"=>{},_=>return Err(fail())}}let incomplete=p.discovery_statistics.values().any(|d|d.permanently_incomplete_catalog);if p.flags.incomplete_catalog!=incomplete||p.flags.complete&&(p.flags.cancelled||p.flags.resource_limited||p.flags.incomplete_catalog){return Err(fail())}
    if !p.resources.wall_elapsed_s.is_finite()||p.resources.wall_elapsed_s<0.0||p.resources.wall_elapsed_s>expected.model.resources.wall_time_s||p.resources.calculator_evaluations>expected.model.resources.total_calculator_evaluations||p.resources.catalog_events>expected.model.resources.catalog_events||p.resources.output_bytes>expected.model.resources.output_bytes||p.resources.resident_memory_bytes>expected.model.resources.resident_memory_bytes||p.resources.saddle_attempts_by_state.values().any(|x|*x>expected.model.resources.saddle_attempts_per_state)||!p.resources.retry_history.is_empty(){return Err(fail())}
    crate::rng::validate_state(&p.rng.trajectory).map_err(|_|fail())?;for(sid,state)in &p.rng.substream_map{if sid.is_empty(){return Err(fail())}crate::rng::validate_state(state).map_err(|_|fail())?;}for event in p.catalog.events.values(){let sid=&event.discovery_provenance.search_id;let stored=p.rng.substream_map.get(sid).ok_or_else(fail)?;let discovering=discovering_state(p,event,policy)?;let derived_search=crate::rng::derive_saddle_substream(p.rng.run_seed,&discovering,&event.discovery_provenance.search_class,event.discovery_provenance.search_index).map_err(|_|fail())?.state();if stored.key!=derived_search.key||stored.initial_counter!=derived_search.initial_counter||crate::rng::substream_digest(&crate::rng::Philox::from_state(stored.clone()).map_err(|_|fail())?)!=event.discovery_provenance.rng_substream_digest{return Err(fail())}}let derived=crate::rng::derive_trajectory_stream(p.rng.run_seed).state();if derived.key!=p.rng.trajectory.key||derived.initial_counter!=p.rng.trajectory.initial_counter{return Err(fail())}
    let mut rng=crate::rng::Philox::new(derived.key,derived.initial_counter);let mut state=p.initial_state.state_id.clone();let mut time=0.0;for(i,step)in p.trajectory.iter().enumerate(){step.rate_table_snapshot.validate().map_err(|_|fail())?;let t=&step.rate_table_snapshot.payload;if step.step_index!=i as u64+1||step.log_sequence!=i as u64+1||step.checkpoint_sequence>p.checkpoint_sequence||step.pre_state_id!=state||t.origin_state_id!=state||step.total_rate_per_s.to_bits()!=t.total_rate_per_s.to_bits(){return Err(fail())}for j in 0..t.event_ids.len(){let event=p.catalog.events.get(&t.event_ids[j]).ok_or_else(fail)?;if event.origin_state_id!=state||event.destination_state_id!=t.destination_state_ids[j]||event.rate_model.log_forward_rate_per_s.to_bits()!=t.log_rates[j].to_bits(){return Err(fail())}}let(us,ut,next)=rng.two_uniforms_atomic().map_err(|_|fail())?;if us.to_bits()!=step.selection_uniform.to_bits()||ut.to_bits()!=step.time_uniform.to_bits(){return Err(fail())}let threshold=us*t.total_rate_per_s;let mut sum=0.0;let mut chosen=t.rates.len()-1;for(j,r)in t.rates.iter().enumerate(){sum+=*r;if sum>threshold{chosen=j;break}}if t.event_ids[chosen]!=step.selected_event_id||t.destination_state_ids[chosen]!=step.post_state_id||t.rates[chosen].to_bits()!=step.selected_rate_per_s.to_bits(){return Err(fail())}let dt=-ut.ln()/t.total_rate_per_s;if (dt-step.time_increment_s).abs()>1e-18+5e-15*dt.abs().max(step.time_increment_s.abs()){return Err(fail())}time+=step.time_increment_s;state=step.post_state_id.clone();rng=next;}if state!=p.current_state.state_id||(time-p.simulation_time_s).abs()>1e-18+5e-15*time.abs().max(p.simulation_time_s.abs())||rng.state()!=p.rng.trajectory{return Err(fail())}Ok(())}
fn validate_state_v2(s:&CommittedStateV2)->Result<(),ApiFailure>{let fail=||ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-ID-006");let mut ids=BTreeSet::new();if s.schema!="spark-atomistic-state/2"||s.identity_version!=IDENTITY_VERSION_V2||s.atom_ids.is_empty()||s.atom_ids.iter().any(|x|x.is_empty()||!ids.insert(x.clone()))||s.species.iter().any(String::is_empty)||s.atom_ids.len()!=s.species.len()||s.atom_ids.len()!=s.positions.len()||s.atom_ids.len()!=s.movable.len()||!s.movable.iter().any(|x|*x)||s.forces_ev_per_angstrom.len()!=s.atom_ids.len()||s.constraints.kind!="fixed-mask"||s.calculator_model_digest.is_empty()||!s.charge.is_finite()||!s.spin.is_finite()||!finite(s.positions.iter().flatten().copied())||!finite(s.cell.iter().flatten().copied())||det(s.cell).abs()<=1e-18||!s.energy_ev.is_finite()||!positive(s.force_tolerance_ev_per_angstrom)||!s.max_movable_force_ev_per_angstrom.is_finite()||s.relaxation_provenance.calculator_identity.is_empty()||s.relaxation_provenance.minimizer_identity.is_empty()||s.relaxation_provenance.termination_reason.is_empty(){return Err(fail())}let system=WireSystem{atom_ids:s.atom_ids.clone(),species:s.species.clone(),positions:s.positions.clone(),cell:s.cell,pbc:s.pbc,movable:s.movable.clone(),constraints:s.constraints.clone(),charge:s.charge,spin:s.spin,calculator_model_digest:s.calculator_model_digest.clone()};let fixed=fixed_contract_digest(&system).map_err(|_|fail())?;let constraint=constraint_digest(&system).map_err(|_|fail())?;let(candidate,state)=state_ids(&system,s.energy_ev).map_err(|_|fail())?;if fixed!=s.fixed_contract_digest||constraint!=s.constraint_digest||candidate!=s.candidate_identity||state!=s.state_id{return Err(fail())}let mut max=0.0_f64;for(i,f)in s.forces_ev_per_angstrom.iter().enumerate(){if !f.iter().all(|x|x.is_finite()){return Err(fail())}if s.movable[i]{max=max.max((f[0]*f[0]+f[1]*f[1]+f[2]*f[2]).sqrt())}}if max.to_bits()!=s.max_movable_force_ev_per_angstrom.to_bits()||max>s.force_tolerance_ev_per_angstrom{return Err(fail())}Ok(())}
fn validate_event_v2(e:&DirectedEventV2,states:&BTreeMap<String,CommittedStateV2>,expected:&ValidatedModel,policy:CheckpointPolicy)->Result<(),ApiFailure>{let fail=||ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-EVENT-001");if e.schema!="spark-atomistic-directed-event/2"||e.environment_key!="disabled"||e.environment_version!="none/1"||e.origin_state_id==e.destination_state_id||e.active_atom_mapping.windows(2).any(|w|w[0]>=w[1])||!e.validation.full_endpoint_relaxations||e.validation.unstable_mode_count!=1||!matches!(e.saddle.evidence_level.as_str(),"HESSIAN"|"DIRECTIONAL")||e.validation.method.is_empty()||(policy==CheckpointPolicy::PreErrata3&&e.validation.method!=e.saddle.evidence_level)||e.saddle.search_id.is_empty()||e.saddle.search_id!=e.discovery_provenance.search_id||e.discovery_provenance.search_class.is_empty()||e.discovery_provenance.rng_substream_digest.is_empty()||e.saddle.termination_reason.is_empty()||e.saddle.positions.is_empty()||!e.saddle.energy_ev.is_finite()||!e.saddle.curvature_ev_per_angstrom2.is_finite()||!e.saddle.forces_ev_per_angstrom.iter().flatten().chain(e.saddle.unstable_direction.iter().flatten()).chain(&e.saddle.orthogonal_curvatures_ev_per_angstrom2).all(|x|x.is_finite())||e.calculator_digest!=expected.model.calculator.model_digest||e.identity_digest!=expected.identity_digest||e.schema_digest!=SCHEMA_DIGEST||e.tolerance_digest!=expected.tolerance_digest{return Err(fail())}let origin=states.get(&e.origin_state_id).ok_or_else(fail)?;let destination=states.get(&e.destination_state_id).ok_or_else(fail)?;if e.validation.calculator_model_digest!=origin.calculator_model_digest||e.validation.constraint_digest!=origin.constraint_digest||e.saddle.positions.len()!=origin.positions.len()||e.saddle.forces_ev_per_angstrom.len()!=origin.positions.len()||e.saddle.unstable_direction.len()!=origin.positions.len()||(e.saddle.evidence_level=="DIRECTIONAL"&&e.saddle.orthogonal_curvatures_ev_per_angstrom2.is_empty()){return Err(fail())}
    // `E2-RATE-001` is the requirement that states the equation -- "Raw barriers are exactly
    // `b_f=E_s-E_i` and `b_r=E_s-E_j`" -- and `E2-CKPT-007`(5) lists "saddle/barrier/rate
    // recomputation" as a step distinct from "event IDs", so a barrier that does not reproduce
    // from its own endpoints is cited to `E2-RATE-001` and not to the `E2-EVENT-001` field table.
    if (e.saddle.energy_ev-origin.energy_ev).to_bits()!=e.barrier_ev.to_bits()||(e.saddle.energy_ev-destination.energy_ev).to_bits()!=e.reverse_barrier_ev.to_bits(){return Err(ApiFailure::new(StatusCode::CheckpointCorrupt,"E2-RATE-001"))}let r=crate::rate::common_prefactor_pair(origin.energy_ev,destination.energy_ev,e.saddle.energy_ev,expected.model.kinetics.temperature,expected.model.kinetics.prefactor,expected.model.kinetics.barrier_tolerance,expected.model.kinetics.detailed_balance_tolerance).map_err(|_|fail())?;if e.rate_model.model!="COMMON_PREFACTOR"||e.rate_model.common_prefactor_per_s.to_bits()!=expected.model.kinetics.prefactor.to_bits()||e.rate_model.temperature_k.to_bits()!=expected.model.kinetics.temperature.to_bits()||e.rate_model.log_forward_rate_per_s.to_bits()!=r.log_forward_rate_per_s.to_bits()||e.rate_model.log_reverse_rate_per_s.to_bits()!=r.log_reverse_rate_per_s.to_bits()||e.rate_model.detailed_balance_residual.to_bits()!=r.detailed_balance_residual.to_bits()||e.selectable!=(e.rate_model.log_forward_rate_per_s>=expected.model.kinetics.log_rate_cutoff){return Err(fail())}let mut left=BTreeSet::new();let mut right=BTreeSet::new();for m in &e.active_atom_mapping{if m[0]>=origin.species.len()||m[1]>=destination.species.len()||!left.insert(m[0])||!right.insert(m[1])||origin.species[m[0]]!=destination.species[m[1]]{return Err(fail())}}let saddle_system=WireSystem{atom_ids:origin.atom_ids.clone(),species:origin.species.clone(),positions:e.saddle.positions.clone(),cell:origin.cell,pbc:origin.pbc,movable:origin.movable.clone(),constraints:origin.constraints.clone(),charge:origin.charge,spin:origin.spin,calculator_model_digest:origin.calculator_model_digest.clone()};let saddle_digest=digest_value(&geometry_certificate(&saddle_system).map_err(|_|fail())?).map_err(|_|fail())?;let(pair,event,reverse)=event_ids(&e.origin_state_id,&e.destination_state_id,&e.saddle,&saddle_digest,&e.active_atom_mapping).map_err(|_|fail())?;if pair!=e.pair_id||event!=e.event_id||reverse!=e.reverse_event_id{return Err(fail())}Ok(())}

#[derive(Clone,Debug,PartialEq)]pub struct DiscoveryChoice{pub search_class:String,pub search_id:String,pub class_stream:PhiloxState,pub saddle_stream:PhiloxState}
pub fn choose_discovery_class(model:&ValidatedModel,state_id:&str,index:u64)->Result<DiscoveryChoice,ApiFailure>{let mut class_rng=saddle_stream(model.model.kinetics.run_seed,state_id,"class-selection",index)?;let u=class_rng.next_uniform().map_err(|_|ApiFailure::new(StatusCode::InternalError,"E2-DISC-001"))?;let mut cumulative=0.0;let mut chosen=model.model.discovery.classes.last().ok_or_else(||ApiFailure::new(StatusCode::InvalidInput,"E2-DISC-001"))?;for class in &model.model.discovery.classes{cumulative+=class.probability;if cumulative>u{chosen=class;break}}let saddle=saddle_stream(model.model.kinetics.run_seed,state_id,&chosen.name,index)?;Ok(DiscoveryChoice{search_class:chosen.name.clone(),search_id:search_id(model.model.kinetics.run_seed,state_id,&chosen.name,index)?,class_stream:class_rng.state(),saddle_stream:saddle.state()})}
pub fn ordered_candidate_ids(ids:&[String])->Result<Vec<String>,ApiFailure>{if ids.iter().any(String::is_empty){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-DISC-003"))}let mut out=ids.to_vec();out.sort();if out.windows(2).any(|w|w[0]==w[1]){return Err(ApiFailure::new(StatusCode::InvalidInput,"E2-DISC-003"))}Ok(out)}
